# Generated by Django 5.1.1 on 2025-05-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientApp', '0005_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientIDCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('counter', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
